server:
  port: 10086

spring:
  cloud:
    loadbalancer: ## Loadbalancer retry
      retry:
        enabled: true
    nacos: ## Nacos Config
      config:
        server-addr: 172.27.153.46:8848/nacos
    gateway: ## Gateway Config
      routes:
        - id: spring-cloud-openfeign  # 路由规则ID，自定义，需要全局唯一
          uri: lb://spring-cloud-openfeign  # 路由目标的微服务名称，一般为 spring.application.name的值，lb表示负载均衡
          predicates: # 路由断言，判断请求是否符合规则，符合则路由到目标
            - Path=/hello/**,/test/** # 以路径(Path)作为规则判断，符合 /hello 开头的则符合，多个用 , 分开
          filters: # 只作用于当前的路由
            - AddRequestHeader=X-Request, blue # 添加请求头过滤器
      default-filters: ## 作用于全部的路由
        - Example=22,wangwu,shenzhen # 自定义的过滤器，名字为ExampleGatewayFilterFactory，这里只需配置Example前缀即可
        - ExampleArgument=18,zhangsan,shenzhen # 快捷方法配置，参数的顺序需要和shortcutFieldOrder方法指定的顺序一致
#        - name: ExampleArgument # 此种方法配置，无需按顺序配置参数
#          args:
#            - age: 19
#              name: lisi
#              address: beijin
